FROM --platform=$BUILDPLATFORM golang:1.20 AS build
LABEL org.opencontainers.image.source=https://github.com/IzumaNetworks/trivial-golang-k8s-deployment
LABEL org.opencontainers.image.description="Trivial Go K8s example"
LABEL org.opencontainers.image.licenses=Apache-2.0
ADD app /app
ARG TARGETOS TARGETARCH
ENV CGO_ENABLED=0
WORKDIR /app
RUN GOOS=$TARGETOS GOARCH=$TARGETARCH go build -o app .
ENTRYPOINT [ "/app/app" ]
